### ISSUE TITLE
Luma Island 1.0.3 Out！Console Enabler is malfunctioning

### ISSUE THREAD

**Issue by apeng0907** [bitterbutt/LumaIslandMods#1]
It can't be used now, even after recompiling with the code you wrote, it still doesn't work

**Comment by bitterbutt** [comment]
> It can't be used now, even after recompiling with the code you wrote, it still doesn't work

It does still work, but the developer changed the default binding to "CTRL + F1" to open the console. I haven't found time to provide rebiding of the key quite yet, unfortunately, but you should be able to open it with that.
